config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'cards', to: 'users/registrations#new_card'
    post 'cards', to: 'users/registrations#create_card'
    #patch 'cards', to: 'users/registrations#update_card'
    #get 'cards_edit', to: 'users/registrations#edit_card'
  end
  root to: "posts#index"
  resources :posts do
    resources :books, only: [:new, :create,:destroy,:show] do
        collection do
          get "sort"
          get "sort_result"
        end
      post "order" , on: :member
      delete "order_destroy" , on: :member
    end
    collection do
      get "search"
      get "sort"
    end
    
  end      
  resources :users, only: [:show] do
    resources :cards, only: [:new, :create, :edit, :update]
  end
  #get "/map_request", to: "posts#map", as: "map_request"
  post "goods/:post_id/create", to: "goods#create" 
  post "goods/:post_id/destroy", to: "goods#destroy"
  get "users/:id/goods", to: "users#goods"
  post "contacts/create", to: "contacts#create"
  get "contacts/new", to: "contacts#new"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :birth_day, presence: true
  has_many :posts, dependent: :destroy
  has_one :card, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :book_orders, dependent: :destroy
  has_many :goods, dependent: :destroy

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
    #   super
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    render :new and return unless @user.valid?

    session['devise.regist_data'] = { user: @user.attributes }
    session['devise.regist_data'][:user]['password'] = params[:user][:password]
    @card = @user.build_card
    render :new_card
    #   super
  end

  def create_card
    @user = User.new(session['devise.regist_data']['user'])

    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    customer = Payjp::Customer.create(
      description: 'test',
      card: params[:card_token]
    )

    @card = Card.new(
      card_token: params[:card_token],
      customer_token: customer.id,
      customercard_token: customer.default_card
    )

    @user.build_card(@card.attributes)
    if @user.save
      session['devise.regist_data']['user'].clear
      NotificationMailer.send_confirm_to_user(@user).deliver
      sign_in(:user, @user)
    else
      render :new_card
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private

  def card_params
    params.require(:address).permit(:postal_code, :address)
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    @user = User.new
    #   super
  end

  # POST /resource/sign_in

  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show]
  def show
    @nickname = current_user.nickname
    @email = current_user.email
    @user = current_user
    @cards = current_user.card
    @posts = @user.posts
    @books = Book.all
    @users = User.find(params[:id])
    @book_orders = BookOrder.all
    @gooduser = User.find_by(id: params[:id])
    @good = Good.where(user_id: @gooduser.id)
    @book_orderpluck = BookOrder.pluck(:book_id)

    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    card = Card.find_by(user_id: current_user.id)

    redirect_to new_card_path and return unless card.present?

    customer = Payjp::Customer.retrieve(card.customer_token)
    @card = customer.cards.first
  end

  # private

  # def move_to_index
  # if current_user != @posts.user || @item.order != nil
  # redirect_to action: :index
  # end
  # end

  # def user_params
  # params.require(:user).permit(:nickname,:email,:encrypted_password)
  # end

  # def set_user
  # @user = User.find(params[:id])
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="facility-show">
  <div class="facility-box-show">
      <div class="facility-show-name">
         <strong><%=@nickname%></strong>
      </div>

  <table class="detail-table-show">
      <tbody>
        <tr>
          <th class="detail-fac">ニックネーム</th>
          <td class="detail-value"><%= @nickname %> </td>
        </tr>
        <tr>
          <th class="detail-fac">登録アドレス</th>
          <td class="detail-value"><%= @email %></td>
        </tr>
      </tbody>
    </table>

    <div class="edit-destroy">
      <%= link_to "ユーザー情報編集", edit_user_registration_path, method: :get, class: "edit-btn" %>
    </div>

      <table class="detail-table-show">
      <tbody>
        <tr>
          <th class="detail-fac">カード番号</th>
          <td class="detail-value"><%= "**** **** **** " + @card[:last4] %> </td>
        </tr>
        <tr>
          <th class="detail-fac">有効期限</th>
          <td class="detail-value"><%= @card[:exp_month] %>/<%= @card[:exp_year] %></td>
        </tr>
      </tbody>
    </table>

        <div class="edit-destroy">
      <%= link_to "クレジットカード情報編集", edit_user_card_path(current_user.id,@cards.id), method: :get, class: "edit-btn" %>
       </div>
</div>

  <div class="facility-resavation">
    <strong>お気に入り</strong>
  </div>
   <div class="facility-list">

   <% if Good.where(user_id: current_user.id).count > 0 %>
    <% @good.each do |good| %>
    <% post = Post.find_by(id: good.post_id) %>
     <% goods_count = Good.where(post_id: post.id).count %>
      <ul class="fac-list">
        <li class="facility-contents-text">
        <div class="facility-image">
          <%= link_to image_tag(post.image, class:"gym1-image" ) , post_path(post.id) %>
        <div class="facility-body">
        <%= link_to post.name, post_path(post.id), class:"facility-title"%>
        <%= link_to post.text, post_path(post.id),  class:"facility-copy-text"%>
        <%= link_to post_path(post.id),  class:"facility-good" do%>
          <a class="good-count-index"><%= goods_count %></a>
          <span class="fas fa-thumbs-up my-orange my-index"><a></a></span>
      <% end %>
        </div>
      </div>
      </li>
    </ul>
    <% end %>
      <% else %>
    <p class="non-contents">現在お気に入りの登録はありません</p>
  <% end %>
  </div>

  <div class="facility-resavation">
    <strong>申込済予約枠</strong>
  </div>

  <div class="facility-list">
        <% if @book_orders.where(user_id: current_user.id).count == 0 || @books.where(start_time: Time.now..Float::INFINITY ).count == 0  || (BookOrder.where(user_id: current_user.id).pluck(:book_id) & @books.where(start_time: Time.now..Float::INFINITY ).pluck(:id)).empty?  %>
           <p class="non-contents">現在申し込み済のご予約はありません</p>
        <% else %>
     <% @book_orders.each do |book_order| %>
      <% if book_order.user_id == current_user.id && book_order.book.end_time.to_s(:datetime_jp) > Time.now.to_s(:datetime_jp) %>
        <ul class="fac-list">
          <li class="facility-contents">
                <%= link_to post_path(book_order.book.post_id), class:"book-btn-detail" do %>
                <div class="book-btn-finished-user">
                <i ></i>
                <% bobst = book_order.book.start_time%>
                <% bobet = book_order.book.end_time%>
                 <p class="start-end-time">
                  <%= book_order.book.post.name %><br></p>
                 
                  <p class="start-end-monthday">
                   <%= bobst.year.to_s(:datetime_jp) %>年
                   <%= bobst.month.to_s(:datetime_jp) %>月
                   <%= bobst.day.to_s(:datetime_jp) %>日<br></p>
                  <p class="start-end-time">
                    <%= bobst.hour.to_s(:datetime_jp) %>時<%= bobst.min.to_s(:datetime_jp) %>分~</p><br>

                  <p class="start-end-monthday">
                   <%= bobet.month.to_s(:datetime_jp) %>月
                   <%= bobet.day.to_s(:datetime_jp) %>日<br></p>
                 <p class="start-end-time">
                   <%= bobet.hour.to_s(:datetime_jp) %>時<%= bobet.min.to_s(:datetime_jp) %>分</p><br>
                  <p class="book-price-memo">
                  ¥<%= book_order.book.price.to_s(:delimited) %><br><br>
                  </div>
                <% end %> 
                <%if Time.now < book_order.book.start_time - 1.hours %>
                <%= link_to order_destroy_post_book_path(book_order.book.post_id,book_order.book.id), method: :delete, data: {confirm: "予約枠を削除しますか？"}, class:"drop-down-one" do%> 
              <ul class="detail-drop-down">
                <li class="drop-down"> 予約枠取消・返金 </li>
              </ul>
              <% end %>
              <% end %>
        </li>
      </ul>
      <% end %>
     <% end %>
    <% end %>
  </div>

    <div class="facility-resavation">
      <strong><%= "#{@nickname}さんの出店"%></strong>
    </div>
    
   <div class="facility-list">
      <% if @posts.where(user_id: current_user.id).count == 0 %>
         <p class="non-contents">現在出店している施設はありません</p>
       <% else %>
    <% @posts.each do |post| %>
     <% goods_count = Good.where(post_id: post.id).count %>
      <ul class="fac-list">
        <li class="facility-contents-text">
        <div class="facility-image">
          <%= link_to image_tag(post.image, class:"gym1-image" ) , post_path(post.id) %>
        <div class="facility-body">
        <%= link_to post.name, post_path(post.id), class:"facility-title"%>
        <%= link_to post.text, post_path(post.id),  class:"facility-copy-text"%>
        <%= link_to post_path(post.id),  class:"facility-good" do%>
          <a class="good-count-index"><%= goods_count %></a>
          <span class="fas fa-thumbs-up my-orange my-index"><a></a></span>
      <% end %>
        </div>
      </div>
      </li>
    </ul>
    <% end %>
   <% end %>
  </div>
</div>