config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'cards', to: 'users/registrations#new_card'
    post 'cards', to: 'users/registrations#create_card'
    #patch 'cards', to: 'users/registrations#update_card'
    #get 'cards_edit', to: 'users/registrations#edit_card'
  end
  root to: "posts#index"
  resources :posts do
    resources :books, only: [:new, :create,:destroy,:show] do
        collection do
          get "sort"
          get "sort_result"
        end
      post "order" , on: :member
      delete "order_destroy" , on: :member
    end
    collection do
      get "search"
      get "sort"
    end
    
  end      
  resources :users, only: [:show] do
    resources :cards, only: [:new, :create, :edit, :update]
  end
  #get "/map_request", to: "posts#map", as: "map_request"
  post "goods/:post_id/create", to: "goods#create" 
  post "goods/:post_id/destroy", to: "goods#destroy"
  get "users/:id/goods", to: "users#goods"
  post "contacts/create", to: "contacts#create"
  get "contacts/new", to: "contacts#new"

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_one :book_order, dependent: :destroy

  validates :start_time, :end_time, :price, presence: true
  validate :end_time_check
  validate :start_check

  def end_time_check
    errors.add(:end_time, 'は開始時刻より遅い時間を選択してください') if start_time > end_time
  end

  def start_check
    errors.add(:start_time, 'は現在の日時より遅い時間を選択してください') if start_time < Time.now
  end

  def self.sort(selection)
    case selection
    when 'new'
      all.order(created_at: :DESC)
    when 'old'
      all.order(created_at: :ASC)
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :destroy, :order, :order_destroy, :move_to_index]
  before_action :authenticate_user!
  before_action :move_to_index, only: [:destroy,:new, :create, :sort, :sort_result]

  def new
    @book = Book.new
    @post = Post.find(params[:post_id])
    @books = @post.books.all
    @booksrev = @post.books.all.reverse
    @book_order = BookOrder.all
    @bookid = Book.find_by(id: params[:book_id])
    @book_orders = BookOrder.pluck(:book_id)
  end

  def create
    @post = Post.find(params[:post_id])
    @books = @post.books.all
    @book_order = BookOrder.all
    @book_orders = BookOrder.pluck(:book_id)
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = '予約を作成しました'
      redirect_to post_path(params[:post_id])
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = '予約を削除しました'
    redirect_to post_path(params[:post_id])
  end

  def order
    @book = Book.find(params[:id])
    redirect_to new_card_path and return unless current_user.card.present?

    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    customer_token = current_user.card.customer_token

    card = Payjp::Charge.create(
      amount: @book.price,
      customer: customer_token,
      currency: 'jpy'
    )
    billing_token = Payjp::Charge.retrieve(card.id).id
    if BookOrder.create(book_id: params[:id], user_id: current_user.id, billing_token: billing_token)
      flash[:notice] = '購入・予約が完了しました'
      redirect_to post_path(params[:post_id])
    end
  end

  def order_destroy
    @book = Book.find(params[:id])
    @book_order = BookOrder.find_by(book_id: @book.id)
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    charge = Payjp::Charge.retrieve(@book_order.billing_token)
    charge.refund

    @book.destroy
    flash[:notice] = '予約を削除・返金しました'
    redirect_to post_path(params[:post_id])
  end

  def sort
    selection = params[:sortword]
    @books = Book.sort(selection)
    @post = Post.find(params[:post_id])
    @book = Kaminari.paginate_array(@post.books.all).page(params[:page]).per(4)
  end

  def sort_result
    @post = Post.find(params[:post_id])
    selection = params[:sortword]
    @book = if selection == 'new'
              Kaminari.paginate_array(@post.books.all.reverse).page(params[:page]).per(4)
            else
              Kaminari.paginate_array(@post.books.all).page(params[:page]).per(4)
            end
  end

  private

  def book_params
    params.require(:book).permit(:start_time, :end_time, :price, :memo, :capacity).merge(user_id: current_user.id,
                                                                                         post_id: params[:post_id])
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def move_to_index
    @post = Post.find(params[:post_id])
    if current_user.id != @post.user_id
      flash[:notice] = 'アクセス権限がありません'
      redirect_to root_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/new.html.erb
<div class="contents row">
  <div class="container">
    <h2>予約枠作成</h2>
    <%= form_with(model:@book,url: post_books_path, local: true) do |f| %>
     <%= render 'shared/error_messages', model: f.object %> 
       

    <div class="form-group">
      <div class="field">
        <div class='form-text-wrap'>
          <label class="form-text">開始時間</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.datetime_field :start_time, class: "input-default" %>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <div class='form-text-wrap'>
          <label class="form-text">終了時間</label>
          <span class="indispensable">必須</span>
        </div>
       <%= f.datetime_field :end_time, class:"input-default" %>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <div class='form-text-wrap'>
          <label class="form-text">料金（円）</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :price,  class:"input-default", placeholder:"1000" %>
      </div>
    </div>

    <!--<div class="form-group">
      <div class="field">
        <div class='form-text-wrap'>
          <label class="form-text">メモ</label>
        </div>
        <%= f.text_field :memo,  class:"input-default", placeholder:"例）割引実施中" %>
      </div>
    </div>-->

      <div class="sign-up">
        <%= f.submit "予約枠を作成する",class:"sign-up-btn" %>        
      </div>
    <% end %>
  </div>
</div>

 <% if (@books.where(post_id: @post.id)).count != 0 %>

   <div class="resavation-delete">
    <strong>未予約枠削除</strong>
  </div>
    <div class="facility-list">
    <% if @books.where(post_id: @post.id).count == 0 || @books.where(start_time: Time.now..Float::INFINITY ).count != 0  &&  @book_order.where(book_id: @bookid) == @bookid || (@book_orders & (@books.where(start_time: Time.now..Float::INFINITY ).ids)).count == ((@books.where(start_time: Time.now..Float::INFINITY ).ids)).count ||  @books.where(start_time: Time.now..Float::INFINITY ).count == 0%>
       <p class="non-contents">現在削除可能な枠はありません</p>
    <% else %>
    
      <% @books.each do |book| %>
      <% if book.book_order == nil && Time.now.to_s(:datetime_jp) < book.start_time.to_s(:datetime_jp) %>
        <ul class="fac-list">
          <li class="facility-contents">
            <div class="book-btn-link" >
           <%= link_to post_book_path(book.post_id,book.id), method: :delete, data: {confirm: "予約枠を削除しますか？"}, class:"book-btn-detail" do %>
              <% bst = book.start_time %>
              <% est = book.end_time %>
               <p class="start-end-monthday">
                <%= bst.year.to_s(:datetime_jp) %>年
                <%= bst.month.to_s(:datetime_jp) %>月
                <%= bst.day.to_s(:datetime_jp) %>日<br></p>
                <p class="start-end-time">
                <%= bst.hour.to_s(:datetime_jp) %>時<%= bst.min.to_s(:datetime_jp) %>分~</p><br>
               
               <p class="start-end-monthday">
                <%= est.month.to_s(:datetime_jp) %>月
                <%= est.day.to_s(:datetime_jp) %>日<br></p>
                <p class="start-end-time">
                <%= est.hour.to_s(:datetime_jp) %>時<%= est.min.to_s(:datetime_jp) %>分</p><br>
                <p class="book-price-memo">
                ¥<%= book.price.to_s(:delimited) %><br>
         <% end %> 
            </div>
          </li>
        </ul>
       <% end %>
      <% end %>
       <% end %>
      <% end %>
      </div>


 <% if @books.where(post_id: @post.id).count != 0 %>
   <div class="resavation-delete">
    <strong>予約済枠削除・返金</strong>
  </div>
    <div class="facility-list">
       <div class="fac-table">
          <p class="table-btn"><%= link_to sort_post_books_path do %>
              <button class="table-btn">予約済一覧を見る</button>
            <% end %></p>
        </div>
     </div>
   <% end %>
       

  

app/views/books/show.html.erb
<div class="contents row">
  <div class="container">
    <h2>予約枠購入確認</h2>
    <%= form_with(model:@book,url: order_post_book_path(@book.post_id,@book.id), method: :post, local: true) do |f| %>

    <div class="form-group">
      <div class="field">
        <div class='form-text-wrap'>
          <label class="form-text">開始時間</label>
        </div>
       <p class="book-confirmation"><%= @book.start_time.to_s(:datetime_jp) %></p>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <div class='form-text-wrap'>
          <label class="form-text">終了時間</label>
        </div>
       <p class="book-confirmation"><%= @book.end_time.to_s(:datetime_jp) %></p>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <div class='form-text-wrap'>
          <label class="form-text">料金</label>
        </div>
       <p class="book-confirmation"> ¥<%= @book.price.to_s(:delimited) %></p>
      </div>
    </div>


     <div class="form-group">
      <div class="field">
        <p>上記内容で予約します。クレジットカードの決済が行われます。</p>
        </div>
    </div>

      <div class="sign-up">
        <%= f.submit "予約をする",class:"sign-up-btn", data: {confirm: "予約枠を購入します。よろしいですか？"} %>        
      </div>
    

    <% end %>
  </div>
</div>

app/views/books/sort.html.erb
   <div class="resavation-delete">
    <strong>予約済枠削除・返金</strong>
  </div>
<div class="facility-table-sort">
  <%= form_with(url: sort_result_post_books_path,  method: :get, local: true, class: "search-form-sort") do |f| %>

    <%= f.select :sortword,[
      ["新しい日付順","new"],
      ["古い日付順","old"],], class: "input-box-sort"%>

     <%= f.submit "並び替える", class:"sort-box" %>
   <% end %>

  <div class="facility-list">
    <% @book.each do |book| %>
     <% if book.book_order != nil %>
        <ul class="fac-list">
          <li class="facility-contents">
            <div class="book-btn-finished" >
           <%= link_to order_destroy_post_book_path(book.post_id,book.id), method: :delete, data: {confirm: "予約枠を削除しますか？"}, class:"book-btn-detail" do %>
              <% bst = book.start_time %>
              <% est = book.end_time %>
               <p class="start-end-monthday">
                <%= bst.year.to_s(:datetime_jp) %>年
                <%= bst.month.to_s(:datetime_jp) %>月
                <%= bst.day.to_s(:datetime_jp) %>日<br></p>
                <p class="start-end-time">
                <%= bst.hour.to_s(:datetime_jp) %>時<%= bst.min.to_s(:datetime_jp) %>分~</p><br>
       
       
               <p class="start-end-monthday">
                <%= est.month.to_s(:datetime_jp) %>月
                <%= est.day.to_s(:datetime_jp) %>日<br></p>
                <p class="start-end-time">
                <%= est.hour.to_s(:datetime_jp) %>時<%= est.min.to_s(:datetime_jp) %>分</p><br>
                <p class="book-price-memo">
                ¥<%= book.price.to_s(:delimited) %><br>
             <% end %> 
            </div>
          </li>
        </ul>
      <% end %>
    <% end %>
  </div>

  <div class="paginate">
    <%= paginate @book %>
  </div>
</div>

app/views/books/sort_result.html.erb
   <div class="resavation-delete">
    <strong>予約済枠削除・返金</strong>
  </div>
<div class="facility-table-sort">
  <%= form_with(url: sort_result_post_books_path,  method: :get, local: true, class: "search-form-sort") do |f| %>

    <%= f.select :sortword,[
      ["新しい日付順","new"],
      ["古い日付順","old"],], class: "input-box-sort"%>

     <%= f.submit "並び替える", class:"sort-box" %>
   <% end %>

  <div class="facility-list">
    <% @book.each do |book| %>
     <% if book.book_order != nil && book.post_id == @post.id %>
        <ul class="fac-list">
          <li class="facility-contents">
            <div class="book-btn-finished" >
           <%= link_to order_destroy_post_book_path(book.post_id,book.id), method: :delete, data: {confirm: "予約枠を削除しますか？"}, class:"book-btn-detail" do %>
              <% bst = book.start_time %>
              <% est = book.end_time %>
               <p class="start-end-monthday">
                <%= bst.year.to_s(:datetime_jp) %>年
                <%= bst.month.to_s(:datetime_jp) %>月
                <%= bst.day.to_s(:datetime_jp) %>日<br></p>
                <p class="start-end-time">
                <%= bst.hour.to_s(:datetime_jp) %>時<%= bst.min.to_s(:datetime_jp) %>分~</p><br>
       
               <p class="start-end-monthday">
                <%= est.month.to_s(:datetime_jp) %>月
                <%= est.day.to_s(:datetime_jp) %>日<br></p>
                <p class="start-end-time">
                <%= est.hour.to_s(:datetime_jp) %>時<%= est.min.to_s(:datetime_jp) %>分</p><br>
                <p class="book-price-memo">
                ¥<%= book.price.to_s(:delimited) %><br>
             <% end %> 
            </div>
          </li>
        </ul>
        <% end %>
    <% end %>
  </div>
  <div class="paginate">
    <%= paginate @book %>
  </div>
</div>