config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'cards', to: 'users/registrations#new_card'
    post 'cards', to: 'users/registrations#create_card'
    #patch 'cards', to: 'users/registrations#update_card'
    #get 'cards_edit', to: 'users/registrations#edit_card'
  end
  root to: "posts#index"
  resources :posts do
    resources :books, only: [:new, :create,:destroy,:show] do
        collection do
          get "sort"
          get "sort_result"
        end
      post "order" , on: :member
      delete "order_destroy" , on: :member
    end
    collection do
      get "search"
      get "sort"
    end
    
  end      
  resources :users, only: [:show] do
    resources :cards, only: [:new, :create, :edit, :update]
  end
  #get "/map_request", to: "posts#map", as: "map_request"
  post "goods/:post_id/create", to: "goods#create" 
  post "goods/:post_id/destroy", to: "goods#destroy"
  get "users/:id/goods", to: "users#goods"
  post "contacts/create", to: "contacts#create"
  get "contacts/new", to: "contacts#new"

end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # belongs_to :prefecture

  validates :postal_code, :prefecture, :city, :address, :price, :bus_hours, :text, :item, :image, presence: true
  validates :postal_code, format: { with: /\A\d{3}-\d{4}\z/, message: 'は無効です。ハイフン（-）を含めて下さい' }

  validates :name, presence: true, length: { maximum: 15 }

  belongs_to :user
  has_many :books, dependent: :destroy
  has_many :goods, dependent: :destroy

  has_one_attached :image
  has_many_attached :images

  # validates :prefecture_id,  numericality: { other_than: 0 }

  def self.search(search)
    if search != ''
      find_by_sql([<<-SQL, "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
      SELECT
        *
      FROM
        posts
      WHERE
        name LIKE ?
        OR postal_code LIKE ?
        OR prefecture LIKE ?
        OR city LIKE ?
        OR address LIKE ?
        OR price LIKE ?
        OR building_name LIKE ?
        OR bus_hours LIKE ?
        OR text LIKE ?
        OR item LIKE ?
        OR caution LIKE ?
      SQL
    else
      Post.all
    end
  end

  #def self.sort(selection)
    #case selection
    #when 'new'
    #  all.order(created_at: :DESC)
  # when 'old'
   #   all.order(created_at: :ASC)
   # when 'likes'
    #  find(Good.group(:post_id).order(Arel.sql('count(post_id) desc')).pluck(:post_id))
   # end
 # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show, :update, :destroy, :likes, :move_to_index,:map]
  before_action :authenticate_user!, except: [:index, :show, :search, :sort]
  before_action :move_to_index, except: [:index, :show, :search, :sort,:new,:create]

  def index
    @post = Post.find_by(params[:id])
    @posts = Post.all.order('created_at DESC')
    @goods_count = Good.where(post_id: @post).count
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = '店舗登録に成功しました'
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def show
    @books = @post.books.all.order('start_time ASC')
    @book = Book.find_by(params[:book_id])
    @book_order = BookOrder.all
    @book_orders = BookOrder.pluck(:book_id)
    @goods_count = Good.where(post_id: @post.id).count
  end

  def edit
  end

  def update
    if params[:post][:image_ids]
      params[:post][:image_ids].each do |image_id|
        image = @post.images.find(image_id)
        image.purge
      end
    end

    if @post.update(post_params)
      flash[:notice] = '店舗情報を更新しました'
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @post.user.id
      @post.destroy
      flash[:notice] = '店舗情報を削除しました'
      redirect_to root_path
    end
  end

  def search
    @posts = Kaminari.paginate_array(Post.search(params[:keyword]).reverse).page(params[:page]).per(4)
    session["search"] = params[:keyword]
    selection = params[:sortword]
  end

  def sort
    selection = params[:sortword]
    if selection == 'new'
      @posts = Kaminari.paginate_array(Post.search(session["search"]).reverse).page(params[:page]).per(4)
    elsif selection == 'likes'
      @posts = Kaminari.paginate_array(Post.find(Good.group(:post_id).order(Arel.sql('count(post_id) desc')).pluck(:post_id))& (Post.search(session["search"]))).page(params[:page]).per(4)
    else
      @posts =  Kaminari.paginate_array(Post.search(session["search"])).page(params[:page]).per(4)
    end
   # @posts = Kaminari.paginate_array(Post.sort(selection)).page(params[:page]).per(2)
   #@post = Kaminari.paginate_array(Post.search(params[:keyword])).page(params[:page]).per(2)
  end


  private

  #def map_address
   # params(:prefecture,:city,:address,:building_name)
  #end

  def post_params
    params.require(:post).permit(:image, :name, :postal_code, :prefecture, :city, :address, :building_name, :price, :bus_hours, :text,
                                 :item, :caution, :youtube_id, images: []).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    if current_user.id != @post.user_id
      flash[:notice] = 'アクセス権限がありません'
      redirect_to action: :index
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
    <% goods_count = Good.where(post_id: post.id).count %>
    <ul class="fac-list">
      <li class="facility-contents-text">
      <div class="facility-image">
        <%= link_to image_tag(post.image, class:"gym1-image" ) , post_path(post.id) %>
      <div class="facility-body">
      <%= link_to post.name, post_path(post.id), class:"facility-title"%>
      <%= link_to post.text, post_path(post.id),  class:"facility-copy-text"%>
      <%= link_to post_path(post.id),  class:"facility-good" do%>
          <a class="good-count-index"><%= goods_count %></a>
          <span class="fas fa-thumbs-up my-orange my-index"><a></a></span>
      <% end %>
      </div>
     </div>
    </li>
  </ul>

app/views/posts/_post_sort.erb
    <% goods_count = Good.where(post_id: post["id"]).count %>
    <ul class="fac-list">
      <li class="facility-contents">
      <div class="facility-image">
        <%= link_to image_tag(@postim.id.image, class:"gym1-image" ) , post_path(post["id"]) %>
      <div class="facility-body">
      <%= link_to post.name, post_path(post["id"]), class:"facility-title"%>
      <%= link_to post.text, post_path(post["id"]),  class:"facility-copy"%>
      <%= link_to post_path(post["id"]),  class:"facility-good" do%>
          <a class="good-count-index"><%= goods_count %></a>
          <span class="fas fa-thumbs-up my-orange my-index"><a></a></span>
      <% end %>
      </div>
     </div>
    </li>
  </ul>

app/views/posts/index.html.erb
<div class="main">
  <div class="title-contents">
      <div class="slider">
        <%= link_to image_tag("top1.png", class:"top-contents"), "#" %>
        <%= link_to image_tag("top2.png", class:"top-contents"), "#" %>
      </div>
  </div>
  <div class="topics-title">
  <strong>Topics</strong>
  </div>
  <table class="topics">
    <tr>
      <th class="topics-date">2021.03.15</th> 
      <td class="topics-sentence"><a> 2月末までご利用でお得なキャンペーン実施中！ </a></td>
    </tr>
    <tr>
      <th class="topics-date">2021.03.10</th> 
      <td class="topics-sentence"><a> 緊急事態宣言の対応について </a></td>
    </tr>
    <tr>
      <th class="topics-date">2021.03.08</th> 
      <td class="topics-sentence"><a> 紹介キャンペーンのご案内 </a></td>
    </tr>
  </table>

  <div>
    <%= image_tag "banner1",class:"index-banner" %>
    <%= image_tag "banner2",class:"index-banner" %>
  </div>

  <% if @posts.empty? %>
  <div class="facility-list-title">
     ログインして施設を投稿しよう
  </div>

  <% else %>

  <div class="facility-list-title">
    <strong>施設一覧</strong>
  </div>
  <div class="facility-table">
  <div class="facility-list-index">
  <% @posts.first(6).each do |post| %>
    <% goods_count = Good.where(post_id: post.id).count %>
    <ul class="fac-list">
      <li class="facility-contents-text">
      <div class="facility-image">
        <%= link_to image_tag(post.image, class:"gym1-image" ) , post_path(post.id) %>
      <div class="facility-body">
      <%= link_to post.name, post_path(post.id), class:"facility-title"%>
      <%= link_to post.text, post_path(post.id),  class:"facility-copy-text"%>
      <%= link_to post_path(post.id),  class:"facility-good" do%>
          <a class="good-count-index"><%= goods_count %></a>
          <span class="fas fa-thumbs-up my-orange my-index"><a></a></span>
      <% end %>
     </div>
     </div>
    </li>
  </ul>
   <% end %>
  <% end %>
   </div>
       <div class="fac-table">
          <p class="table-btn"><%= link_to search_posts_path do %>
              <button class="table-btn">一覧を見る</button>
            <% end %></p>
        </div>
  </div>
</div>

app/views/posts/map.js.erb
(function(){
  let pos = new google.maps.LatLng(
   <%= @latlng[0] %>, 
   <%= @latlng[1] %>  
  );

  mapInstance.setCenter(pos)
  let marker = new google.maps.Marker({
    map: mapInstance,
    position: pos
  });
})()

app/views/posts/search.html.erb
<div class="facility-table-sort">
  <%= form_with(model:@post, url: sort_posts_path,  method: :get, local: true, class: "search-form-sort") do |f| %>


    <%= f.select :sortword,[
      ["投稿が新しい順","new"],
      ["投稿が古い順","old"],
      ["いいねが多い順","likes"],], class: "input-box-sort"%>

     <%= f.submit "並び替える", class:"sort-box" %>

  <% end %>
  
  <div class="facility-table">
  <div class="facility-list-index">
    <% @posts.each do |post| %>
      <%= render partial: "post", locals: { post: post } %>
    <% end %>
  </div>
  </div>
  <div class="paginate">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="facility-show">
  <div class="facility-box-show">
      <div class="facility-show-name">
         <strong><%= @post.name %></strong>
      </div>
      <div class="fac-img-content">
         <%=link_to image_tag(@post.image, class:"gym1-image-show") ,class:"fac-box-img" %>
      </div>

    <% if @post.images.blobs.present?  %>
      <p>
        <strong>店舗画像</strong>
      <div class="slider-show">
          <% @post.images.each do |image|%>
            <%= image_tag(image, class:"slide-image")%>
          <% end %>
      </div>
      </p>
    <% end %>


   <div class="fac-img-content">
    <% if @post.youtube_id.present? %>
      <div style="position: relative; padding-bottom: 56.25%;", class="youtube">
        <iframe 
          style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" 
          src="https://www.youtube.com/embed/<%= @post.youtube_id %>" 
          frameborder="0" 
          allow="autoplay; 
          encrypted-media" 
          allowfullscreen>
        </iframe>
      </div>
      <% end %>
  </div>

    <div id="goods_<%= @post.id %>">
      <%= render partial: "goods/good", locals:{ post:@post,goods_count:@goods_count } %>
    </div>
      
      <div id="map" class="map-window"></div>
      <script type="text/javascript">
        var map;
        var marker;
        var geocoder;
        function initMap() {
          geocoder = new google.maps.Geocoder();
          geocoder.geocode({
          'address': '<%= @post.prefecture+@post.city+@post.address+@post.building_name %>' 
          }, function(results, status) {
            if (status === google.maps.GeocoderStatus.OK) {
            map = new google.maps.Map(document.getElementById('map'), {
              center: results[0].geometry.location,
              zoom: 17
          });
          marker = new google.maps.Marker({
          position: results[0].geometry.location,
          map: map
          });

          } else {
            alert(status);
          } 
        });
      }
      </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['MAP_API_KEY']%>&callback=initMap" async></script>
      

       <% if user_signed_in? && current_user.id == @post.user_id %>
        <div class="edit-destroy">
          <%= link_to "予約枠作成/削除", new_post_book_path(@post.id), method: :get, class: "show-edit-btn" %>
          <%= link_to "編集", edit_post_path(@post.id), method: :get, class: "show-edit-btn" %>
          <%= link_to "削除", post_path(@post.id), method: :delete, class:"destroy-botton", data: {confirm: "店舗情報を削除しますか？"} %>
        </div>
      <% end %>
  </div>
  
  <table ~~~ class="detail-table-show">
      <tbody>
        <tr>
          <th class="detail-fac">住所</th>
          <td class="detail-value"><%= @post.prefecture+@post.city+@post.address+@post.building_name %> </td>
        </tr>
        <tr>
          <th class="detail-fac">料金</th>
          <td class="detail-value"><%= @post.price %></td>
        </tr>
        <tr>
          <th class="detail-fac">営業時間</th>
          <td class="detail-value"><%= @post.bus_hours %></td>
        </tr>
        <tr>
          <th class="detail-fac">施設説明</th>
          <td class="detail-value"> <%= @post.text %></td>
        </tr>
        <tr>
          <th class="detail-fac">アイテム</th>
          <td class="detail-value"><%= @post.item %> </td>
        </tr>
        <% if @post.caution != "" %>
        <tr>
          <th class="detail-fac">注意事項</th>
          <td class="detail-value"> <%= @post.caution %> </td>
        </tr>
       <% end  %>
      </tbody>
    </table>
 <% if user_signed_in?  &&  current_user.id == @post.user_id %>
    <div class="facility-resavation">
      <strong>現在の予約可能枠</strong>
    </div>
    <div class="facility-list">
    <% if @books.where(post_id: @post.id).count == 0 || @books.where(start_time: Time.now..Float::INFINITY ).count != 0 && @book_order.where(book_id: @book) == nil || (@book_orders & (@books.where(start_time: Time.now..Float::INFINITY ).ids)).count == ((@books.where(start_time: Time.now..Float::INFINITY ).ids)).count ||  @books.where(start_time: Time.now..Float::INFINITY ).count == 0 %>
       <p class="non-contents">現在ご予約可能な枠はありません</p>
    <% else %>
    <% @books.each do |book| %>
     <% if book.book_order == nil && Time.now.to_s(:datetime_jp) < book.start_time.to_s(:datetime_jp)%>
      <ul class="fac-list">
        <li class="facility-contents">
          <div class="book-btn">
              <div class="book-btn-detail"> 
              <i ></i>
              <% bst = book.start_time %>
              <% est = book.end_time %>
               <a class="start-end-monthday">
                <%= bst.year.to_s(:datetime_jp) %>年
                <%= bst.month.to_s(:datetime_jp) %>月
                <%= bst.day.to_s(:datetime_jp) %>日<br></a>
                <a class="start-end-time">
                <%= bst.hour.to_s(:datetime_jp) %>時<%= bst.min.to_s(:datetime_jp) %>分~</a><br>

               <a class="start-end-monthday">
                <%= est.month.to_s(:datetime_jp) %>月
                <%= est.day.to_s(:datetime_jp) %>日<br></a>
                <a class="start-end-time">
                <%= est.hour.to_s(:datetime_jp) %>時<%= est.min.to_s(:datetime_jp) %>分</a><br>
                <a class="book-price-memo">
                ¥<%= book.price.to_s(:delimited) %><br>
                <%= book.memo %></a>
                </div>
          </div>
      </li>
    </ul>
     <% end %>
    <% end %> 
     <% end %> 
    </div>

    <div class="facility-resavation">
      <strong>予約完了枠</strong>
    </div>
    <div class="facility-list">

  <div class="fac-table">
    <p class="table-btn"><%= link_to sort_post_books_path(@post.id) do %>
        <button class="table-btn">予約済一覧を見る</button>
      <% end %></p>
  </div>

    </div>
   <% elsif user_signed_in? %>
     <div class="facility-resavation">
    <strong>ご利用のご予約はこちらから</strong>
  </div>
  <div class="facility-list">
    <% if @books.where(post_id: @post.id).count == 0 || @books.where(start_time: Time.now..Float::INFINITY ).count != 0 && @book_order.where(book_id: @book) == nil || (@book_orders & (@books.where(start_time: Time.now..Float::INFINITY ).ids)).count == ((@books.where(start_time: Time.now..Float::INFINITY ).ids)).count ||  @books.where(start_time: Time.now..Float::INFINITY ).count == 0 %> 
       <p class="non-contents">現在ご予約可能な枠はありません</p>
    <% else %>
  <% @books.each do |book| %>
  <% if book.book_order == nil && Time.now.to_s(:datetime_jp) < book.start_time.to_s(:datetime_jp) %>
    <ul class="fac-list">
      <li class="facility-contents">
            <%= link_to post_book_path(book.post_id,book.id), class:"book-btn-detail" do %>
             <div class="book-btn-link">
             <i ></i>
              <% bst = book.start_time %>
              <% est = book.end_time %>
               <p class="start-end-monthday">
                <%= bst.year.to_s(:datetime_jp) %>年
                <%= bst.month.to_s(:datetime_jp) %>月
                <%= bst.day.to_s(:datetime_jp) %>日<br></p>
                <p class="start-end-time">
                <%= bst.hour.to_s(:datetime_jp) %>時<%= bst.min.to_s(:datetime_jp) %>分~</p><br>

               <p class="start-end-monthday">
                <%= est.month.to_s(:datetime_jp) %>月
                <%= est.day.to_s(:datetime_jp) %>日<br></p>
                <p class="start-end-time">
                <%= est.hour.to_s(:datetime_jp) %>時<%= est.min.to_s(:datetime_jp) %>分</p><br>
                <p class="book-price-memo">
                ¥<%= book.price.to_s(:delimited) %><br>
                <!--<%= book.memo %>--></p>
              </div>
            <% end %> 
     </li>
   </ul>
   <% end %>
   <% end %>
   </div>
  <% end %>
   <% else %>
     <div class="facility-resavation">
    会員登録後、ご予約頂けます
  </div>
  <% end %>
</div>
</div>

app/views/posts/show2.html.erb
 
  
    <% if @books.where(post_id: @post.id).count == 0 || @books.where(start_time: Time.now..Float::INFINITY ).count == 0 && @book_order.where(book_id: @book) == @book ||  @book_order.empty? || (@book_orders & (@books.where(start_time: Time.now..Float::INFINITY ).ids)).count != ((@books.where(start_time: Time.now..Float::INFINITY ).ids)).count  ||@books.where(start_time: Time.now..Float::INFINITY ).count == 0 %>
       <p class="non-contents">現在ご予約済の枠はありません</p>
    <% else %>
    <% @books.each do |book| %>
    <% if book.book_order != nil  && Time.now.to_s(:datetime_jp) < book.start_time.to_s(:datetime_jp) %>
      <ul class="fac-list">
        <li class="facility-contents">
          <div class="book-btn-finished">
              <%= link_to "#", class:"book-btn-detail" do %>
              <i ></i>
              <% bst = book.start_time %>
              <% est = book.end_time %>
               <p class="start-end-monthday">
                <%= bst.year.to_s(:datetime_jp) %>年
                <%= bst.month.to_s(:datetime_jp) %>月
                <%= bst.day.to_s(:datetime_jp) %>日<br></p>
                <p class="start-end-time">
                <%= bst.hour.to_s(:datetime_jp) %>時<%= bst.min.to_s(:datetime_jp) %>分~</p><br>

               <p class="start-end-monthday">
                <%= est.month.to_s(:datetime_jp) %>月
                <%= est.day.to_s(:datetime_jp) %>日<br></p>
                <p class="start-end-time">
                <%= est.hour.to_s(:datetime_jp) %>時<%= est.min.to_s(:datetime_jp) %>分</p><br>
                <p class="book-price-memo">
                ¥<%= book.price.to_s(:delimited) %><br>
                <% end %>
          </div>
      </li>
    </ul>
    <% end %>
    <% end %>
    <% end %> 

     <!-- book new の削除選択肢 -->

         <% if @books.where(post_id: @post.id).count == 0 || @books.where(start_time: Time.now..Float::INFINITY ).count == 0 && @book_order.where(book_id: @bookid) == @bookid || @book_order.empty? || (@book_orders & (@books.where(start_time: Time.now..Float::INFINITY ).ids)).count != ((@books.where(start_time: Time.now..Float::INFINITY ).ids)).count%>
       <p class="non-contents">現在削除可能な枠はありません</p>
    <% else %>

      <% @booksrev.first(6).each do |book| %>
        <% if book.book_order != nil %>
        <ul class="fac-list">
          <li class="facility-contents">
            <div class="book-btn-finished" >
           <%= link_to order_destroy_post_book_path(book.post_id,book.id), method: :delete, data: {confirm: "予約枠を削除しますか？"}, class:"book-btn-detail" do %>
              <% bst = book.start_time %>
              <% est = book.end_time %>
               <p class="start-end-monthday">
                <%= bst.year.to_s(:datetime_jp) %>年
                <%= bst.month.to_s(:datetime_jp) %>月
                <%= bst.day.to_s(:datetime_jp) %>日<br></p>
                <p class="start-end-time">
                <%= bst.hour.to_s(:datetime_jp) %>時<%= bst.min.to_s(:datetime_jp) %>分~</p><br>

     
       
               <p class="start-end-monthday">
                <%= est.month.to_s(:datetime_jp) %>月
                <%= est.day.to_s(:datetime_jp) %>日<br></p>
                <p class="start-end-time">
                <%= est.hour.to_s(:datetime_jp) %>時<%= est.min.to_s(:datetime_jp) %>分</p><br>
                <p class="book-price-memo">
                ¥<%= book.price.to_s(:delimited) %><br>
         <% end %> 
            </div>
          </li>
        </ul>
     <% end %>
      <% end %>
      <% end %>
      
      render partial: "post_sort", locals: { post: post }

      @posts = Kaminari.paginate_array((Post.search(session["search"]) & Post.find(Good.group(:post_id).order(Arel.sql('count(post_id) desc')).pluck(:post_id)))).page(params[:page]).per(4)


          <script>
    let map
    let geocoder

    function initMap() {
    geocoder = new google.maps.Geocoder()
    map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 35.661777, lng: 139.704051},
        zoom: 8
    });
    }
    
      function codeAddress(){
        let inputAddress = document.getElementById('<%= @post.prefecture+@post.city+@post.address+@post.building_name %>').value;
        geocoder.geocode( { '<%= @post.prefecture+@post.city+@post.address+@post.building_name %>': inputAddress}, function(results, status) {
          if (status == 'OK') {
      // map.setCenterで地図が移動
            map.setCenter(results[0].geometry.location);
      // google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
            var marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
            });
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
      }
    </script>
  <script src = "https://maps.googleapis.com/maps/api/js?key=<%=ENV['MAP_API_KEY']%>&callback=initMap" async defer></script>

app/views/posts/sort.html.erb
<div class="facility-table-sort">
  <%= form_with(url: sort_posts_path,  method: :get, local: true, class: "search-form-sort") do |f| %>

    <%= f.select :sortword,[
      ["投稿が新しい順","new"],
      ["投稿が古い順","old"],
      ["いいねが多い順","likes"],], class: "input-box-sort"%>

     <%= f.submit "並び替える", class:"sort-box" %>
   <% end %>
  <div class="facility-table">
  <div class="facility-list-index">
    <% @posts.each do |post| %>
      <%= render partial: "post", locals: { post: post }%>
    <% end %>
  </div>
  </div>
  <div class="paginate">
    <%= paginate @posts %>
  </div>
</div>